### ISSUE TITLE
Update getpartialquarterpercent function to use inactive date

### ISSUE THREAD

**Issue by cmaxson08** [zkeene/scorecard#36]

**Comment by zkeene** [comment]
inactive date was not being pulled in by getContract, added field to function. Added array element to function calls to getContractStatusArray and getPartialQuarterPercent. Need to adjust getContractStatusArray to go to partial based on inactive date and then adjust getPartialQuarterPercent to account for it as well.

**Comment by zkeene** [comment]
updates pushed to master branch, will leave open in case there are issues
