### ISSUE TITLE
Need ability to quarterly targets for AWVs

### ISSUE THREAD

**Issue by zkeene** [zkeene/scorecard#39]

**Comment by zkeene** [comment]
How are we handling period targets? Do they need to be specified as well? @christinakettering12345

**Comment by zkeene** [comment]
![image](https://user-images.githubusercontent.com/19367564/74608557-0b2a2900-50b0-11ea-86b7-be49a11bd296.png)
How does this look @christinakettering12345

**Comment by christinakettering12345** [comment]
This looks good, but we only need one target per quarter.

**Comment by christinakettering12345** [comment]
Cardiology does not have AWV so we do not need period based targets

**Comment by zkeene** [comment]
This feature has been implemented
