### ISSUE TITLE
provider 346 was prorated but scorecard is still giving full prorated amount on metrics she didnt meet top threshold

### ISSUE THREAD

**Issue by cmaxson08** [zkeene/scorecard#50]
provider 346 was prorated but scorecard is still giving full prorated amount on metrics she didnt meet top threshold

**Comment by zkeene** [comment]
Possible causes:
**pay cycle** - only affects when the total incentive is displayed at the bottom of the contract

**contract status array**
provider 346 results in q1-3 ineligible and q4 partial whether def date is populated or not
provider 49 (has a effective date in 2018) results in def/def/part/elig if def date populated, defx4 if no date populated
this suggests the getContractStatusArray function is handling status differently depending on if a provider becomes effective in the year - will investigate this further as likely cause

**Comment by zkeene** [comment]
### Current Contract Status Logic

Attempts to match going down this list

**Full Year Eligible**
Effective before Year Start & Default Expire before Year Start & (Inactive after Year End OR Inactive Blank)
**Full Year Default**
Effective before Year Start & (Default Expire after Year End OR Default Blank) & (Inactive after Year End OR Inactive Blank)
**Full Year Ineligible**
Effective after Year End OR Effective Blank OR (Inactive before Year Start & Inactive NOT Blank)
**Not Full Year - Evaluate Quarter by Quarter**
**Quarter Eligible**
Effective before Qtr Start & Default Expire before Qtr Start & (Inactive after Qtr End OR Inactive Blank)
**Quarter Default**
Effective before Qtr Start & (Default Expire after Qtr End OR Default Blank) & (Inactive after Qtr End OR Inactive Blank)
**Quarter Ineligible**
Effective after Qtr End OR Effective Blank OR (Inactive before Qtr Start & Inactive NOT Blank)
**Quarter Partial - Sets if nothing else is met**

**Comment by zkeene** [comment]
@cmaxson08 @christinakettering12345 
Default Expire Before Year/Qtr Start evaluates true if not set, which is causing the issue. We need to discuss how we want it to behave if a default is not set. I would recommend we set it to evaluate false if not set.

**Comment by zkeene** [comment]
added `AND !$default_is_null` to default expire before start logic
