### ISSUE TITLE
Ortho Q3 2020

### ISSUE THREAD

**Issue by cmaxson08** [zkeene/scorecard#57]
Original:

- LOS-not a beta metric

- Close the Referral Loop-beta metric

What they want:

- LOS stays on as a beta metric

- Close the Referral Loop-not a beta metric

What I did:

- Created new close the referral loop metric with thresholds (so theres a regular and a beta)

- Duplicated LOS specific metric instead of creating new beta metric so now theres 2 of the same metric. Need to leave old one on for data purposes. need to get rid of duplicate & create separate beta metric

**Comment by zkeene** [comment]
Cleaned up unnecessary records and created appropriate new records. System is not calculating payment correctly though, it is assuming the LOS is still something that should be included in payment when it shouldn't. Will likely require quarterly specific metrics if we want it to work as expected.
